### ISSUE TITLE
Improve on token handling

### ISSUE THREAD

**Issue by big-kahuna-burger** [davidguttman/authentic-client#2]
`authentic-client` uses jsonist anyway, so instead of making authenticated requests with authentic-client, and unauthenticated requests with jsonist, we could have authentic-client:

1. check the existence/expiration of a token before making each request
2. keep the token cached
3. insert the token into all requests
4. (bonus) allow unauthenticated requests

**Comment by davidguttman** [comment]
Sounds great!

**Comment by davidguttman** [comment]
One thing to keep in mind is that AC can get the expiry information by getting the public key and decrypting the token.
